import pg from 'pg';

import { env } from './env.js';
import { logger } from './logger.js';

const { Pool } = pg;

let pool;
let pgPool;

const replacePlaceholders = (sql) => {
  let index = 0;
  return sql.replace(/\?/g, () => `$${++index}`);
};

const normalizeInsertSql = (sql) => {
  if (!/^\s*insert\b/i.test(sql) || /\breturning\b/i.test(sql)) {
    return sql;
  }

  return `${sql.trimEnd()} RETURNING id`;
};

const toQueryConfig = (sql, params = []) => ({
  text: normalizeInsertSql(replacePlaceholders(sql)),
  values: params,
});

const getStatementType = (sql) => sql.trim().split(/\s+/, 1)[0]?.toUpperCase() ?? '';

const toLegacyResult = (sql, result) => {
  const statementType = getStatementType(sql);
  const insertId = result.rows[0]?.id ?? null;

  if (statementType === 'SELECT') {
    return [result.rows, undefined];
  }

  if (statementType === 'INSERT') {
    return [{ insertId, rowCount: result.rowCount, rows: result.rows }, undefined];
  }

  return [{ rowCount: result.rowCount, rows: result.rows }, undefined];
};

const createQueryInterface = (client) => ({
  async query(sql, params = []) {
    const result = await client.query(toQueryConfig(sql, params));
    return toLegacyResult(sql, result);
  },
});

const ensureColumn = async (tableName, columnName, definition) => {
  const [rows] = await pool.query(
    `SELECT 1
       FROM information_schema.columns
      WHERE table_schema = current_schema()
        AND table_name = ?
        AND column_name = ?
      LIMIT 1`,
    [tableName, columnName],
  );

  if (rows.length > 0) {
    return;
  }

  await pool.query(`ALTER TABLE ${tableName} ADD COLUMN ${columnName} ${definition}`);
};

const ensureUpdatedAtTrigger = async (tableName) => {
  const triggerName = `${tableName}_set_updated_at`;

  await pool.query(
    `DO $$
     BEGIN
       IF NOT EXISTS (
         SELECT 1
           FROM pg_trigger
          WHERE tgname = '${triggerName}'
       ) THEN
         CREATE TRIGGER ${triggerName}
         BEFORE UPDATE ON ${tableName}
         FOR EACH ROW
         EXECUTE FUNCTION set_updated_at();
       END IF;
     END
     $$`,
  );
};

const createTables = async () => {
  await pool.query(`
    CREATE OR REPLACE FUNCTION set_updated_at()
    RETURNS TRIGGER AS $$
    BEGIN
      NEW.updated_at = NOW();
      RETURN NEW;
    END;
    $$ LANGUAGE plpgsql
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS users (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name VARCHAR(80) NOT NULL,
      email VARCHAR(255) NOT NULL,
      password VARCHAR(255) NOT NULL,
      role VARCHAR(20) NOT NULL DEFAULT 'staff'
        CHECK (role IN ('admin', 'staff', 'guest')),
      is_guest BOOLEAN NOT NULL DEFAULT FALSE,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      CONSTRAINT uq_users_email UNIQUE (email)
    )
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS parties (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name VARCHAR(120) NOT NULL,
      phone VARCHAR(20) NOT NULL,
      gstin VARCHAR(30),
      current_balance NUMERIC(12,2) NOT NULL DEFAULT 0,
      status VARCHAR(2) NOT NULL DEFAULT 'Dr'
        CHECK (status IN ('Dr', 'Cr')),
      opening_balance NUMERIC(12,2) NOT NULL DEFAULT 0,
      last_payment_date TIMESTAMPTZ,
      total_debit NUMERIC(12,2) NOT NULL DEFAULT 0,
      total_credit NUMERIC(12,2) NOT NULL DEFAULT 0,
      closing_balance NUMERIC(12,2) NOT NULL DEFAULT 0,
      created_by BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);

  await pool.query('CREATE INDEX IF NOT EXISTS idx_parties_created_by ON parties (created_by)');
  await pool.query('CREATE INDEX IF NOT EXISTS idx_parties_name ON parties (name)');

  await ensureColumn('parties', 'gstin', 'VARCHAR(30)');

  await pool.query(`
    CREATE TABLE IF NOT EXISTS ledger_entries (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      party_id BIGINT NOT NULL REFERENCES parties (id) ON DELETE CASCADE,
      date TIMESTAMPTZ NOT NULL,
      type VARCHAR(20) NOT NULL
        CHECK (type IN ('opening_balance', 'sale', 'payment')),
      reference VARCHAR(120) NOT NULL,
      invoice_data TEXT,
      debit_amount NUMERIC(12,2),
      credit_amount NUMERIC(12,2),
      balance NUMERIC(12,2) NOT NULL,
      status_label VARCHAR(30) NOT NULL,
      created_by BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);

  await pool.query('CREATE INDEX IF NOT EXISTS idx_ledger_party_date ON ledger_entries (party_id, date)');
  await pool.query('CREATE INDEX IF NOT EXISTS idx_ledger_created_by_date ON ledger_entries (created_by, date)');

  await ensureColumn('ledger_entries', 'invoice_data', 'TEXT');
  await ensureUpdatedAtTrigger('users');
  await ensureUpdatedAtTrigger('parties');
  await ensureUpdatedAtTrigger('ledger_entries');
};

export const connectDatabase = async () => {
  pgPool = new Pool({
    connectionString: env.databaseUrl,
    max: env.dbConnectionLimit,
    ssl: env.dbSsl ? { rejectUnauthorized: false } : false,
  });

  pool = createQueryInterface(pgPool);
  await pool.query('SELECT 1');
  await createTables();
  logger.info('Connected to PostgreSQL');
};

export const getPool = () => {
  if (!pool) {
    throw new Error('Database pool has not been initialized');
  }

  return pool;
};

export const withTransaction = async (handler) => {
  if (!pool) {
    throw new Error('Database pool has not been initialized');
  }

  const client = await pgPoolConnect();
  const connection = createQueryInterface(client);

  try {
    await client.query('BEGIN');
    const result = await handler(connection);
    await client.query('COMMIT');
    return result;
  } catch (error) {
    await client.query('ROLLBACK');
    throw error;
  } finally {
    client.release();
  }
};

const pgPoolConnect = async () => {
  if (!pgPool) {
    throw new Error('Database pool has not been initialized');
  }

  return pgPool.connect();
};
