create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name varchar(80) not null,
  email varchar(255) not null unique,
  password varchar(255) not null,
  role varchar(20) not null default 'staff' check (role in ('admin', 'staff', 'guest')),
  is_guest boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.parties (
  id bigint generated by default as identity primary key,
  name varchar(120) not null,
  phone varchar(20) not null,
  gstin varchar(30),
  current_balance numeric(12,2) not null default 0,
  status varchar(2) not null default 'Dr' check (status in ('Dr', 'Cr')),
  opening_balance numeric(12,2) not null default 0,
  last_payment_date timestamptz,
  total_debit numeric(12,2) not null default 0,
  total_credit numeric(12,2) not null default 0,
  closing_balance numeric(12,2) not null default 0,
  created_by bigint not null references public.users (id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ledger_entries (
  id bigint generated by default as identity primary key,
  party_id bigint not null references public.parties (id) on delete cascade,
  date timestamptz not null,
  type varchar(20) not null check (type in ('opening_balance', 'sale', 'payment')),
  reference varchar(120) not null,
  invoice_data jsonb,
  debit_amount numeric(12,2),
  credit_amount numeric(12,2),
  balance numeric(12,2) not null,
  status_label varchar(30) not null,
  created_by bigint not null references public.users (id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_parties_created_by on public.parties (created_by);
create index if not exists idx_parties_name on public.parties (name);
create index if not exists idx_ledger_party_date on public.ledger_entries (party_id, date);
create index if not exists idx_ledger_created_by_date on public.ledger_entries (created_by, date);

drop trigger if exists users_set_updated_at on public.users;
create trigger users_set_updated_at
before update on public.users
for each row
execute function public.set_updated_at();

drop trigger if exists parties_set_updated_at on public.parties;
create trigger parties_set_updated_at
before update on public.parties
for each row
execute function public.set_updated_at();

drop trigger if exists ledger_entries_set_updated_at on public.ledger_entries;
create trigger ledger_entries_set_updated_at
before update on public.ledger_entries
for each row
execute function public.set_updated_at();
